cluster.name: elasticsearch-cluster
node.name: es-node1
network.host: 0.0.0.0
#network.publish_host: 10.191.51.45
http.port: 9200
transport.tcp.port: 9300
http.cors.enabled: true
http.cors.allow-origin: "*"
node.master: true
node.data: true
discovery.zen.minimum_master_nodes: 1

# 如果是多节点es，通过ping来健康检查
# discovery.zen.ping.unicast.hosts: ["172.16.1.3:9300", "172.16.1.4:9300"]
#discovery.zen.fd.ping_timeout: 120s
#discovery.zen.fd.ping_retries: 3
#discovery.zen.fd.ping_interval: 30s
#cluster.info.update.interval: 1m

indices.fielddata.cache.size:  20%
indices.breaker.total.limit: 60%
indices.recovery.max_bytes_per_sec: 100mb
indices.memory.index_buffer_size: 20%
script.painless.regex.enabled: true

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true