version: '3'
services:
  zk:
    image: wurstmeister/zookeeper
    restart: always
    container_name: zk
    hostname: zk
    networks:
      - "kafka-net"
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    restart: always
    ports:
      - "9092:9092"
    networks:
      - "kafka-net"
    environment:
      TZ: "Asia/Shanghai"
      LANG: "en_US.UTF-8"
      KAFKA_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: CLIENT://47.97.205.190:9092,EXTERNAL://47.97.205.190:9093    ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zk

  kafka-manager:
    image: sheepkiller/kafka-manager              ## 镜像：开源的web管理kafka集群的界面
    container_name: kafka-manager
    environment:
        ZK_HOSTS: "47.97.205.190:2181"                   ## 修改:宿主机IP
    ports:
      - "9000:9000"                               ## 暴露端口

networks:
  kafka-net:
    driver: bridge