version: '3'

networks:
  databus:
    driver: bridge

services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "test"
    image: "mysql:5.7"
    restart: always
    container_name: "databus-mysql"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf/my.cnf:/etc/my.cnf"
    ports:
      - "3306:3306"
    networks:
      - databus

  zk:
    image: wurstmeister/zookeeper
    restart: always
    container_name: databus-zk
    ports:
      - 2181:2181
    volumes:
      - ./zk/data:/data
      - ./zk/data:/datalog
    networks:
      - databus

  kafka:
    image: wurstmeister/kafka       ## 镜像
    container_name: "databus-kafka"
    ports:
      - "9092:9092"
    networks:
      - databus
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zk:2181       ## 卡夫卡运行是基于zookeeper的
      KAFKA_ADVERTISED_HOST_NAME: kafka   ## 修改:宿主机IP
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DELETE_RETENTION_MS: 1000
      # KAFKA_CREATE_TOPICS: binlog-test ## 设置主题
    depends_on:
      - zk

  # kafka-manager:
  #   image: sheepkiller/kafka-manager                ## 镜像：开源的web管理kafka集群的界面
  #   environment:
  #     ZK_HOSTS: zk:2181
  #     KAFKA_BROKERS: kafka:9092
  #   restart: always
  #   container_name: "databus-kafka-manager"
  #   networks:
  #     - databus
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - kafka
  #     - zk

  kafka-eagle:
    image: kafka-eagle:v2.0.3
    container_name: kafka-eagle
    restart: always
    depends_on:
      - kafka
      - zk
    networks:
      - databus
    ports:
      - "8048:8048"
    environment:
      ZKSERVER: "zk:2181"
    volumes:
      - ./kafka-eagle/conf/system-config.properties:/kafka-eagle/conf/system-config.properties
      - ./kafka-eagle/logs:/kafka-eagle/logs

  canal:
    image: canal/canal-server:v1.1.4
    container_name: databus-canal
    networks:
      - databus
    ports:
      - 11111:11111
    environment:
      - canal.instance.mysql.slaveId=100 ##mysql slaveId 唯一
      - canal.auto.scan=false
      - canal.destinations=test
      - canal.instance.master.address=mysql:3306  ##mysql地址
      - canal.instance.dbUsername=canal ##mysql用户
      - canal.instance.dbPassword=123456 ##mysql密码
      - canal.serverMode=kafka
      - canal.mq.servers=kafka:9092
      - canal.mq.flatMessage=true
      - canal.mq.compressionType=none
      - canal.mq.acks=all
      - canal.mq.partition=0
      - canal.mq.bufferMemory=33554432
      - canal.mq.retries=0
      - canal.mq.topic=binlog-test
      - canal.instance.filter.regex=test.t_user
    volumes:
      - ./canal/conf:/canal-server/conf
      - ./canal/data:/canal-server/logs
    depends_on:
      - mysql
      - kafka
  redis:
    image: redis
    container_name: databus_redis
    networks:
      - databus
    ports:
      - 6379:6379
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
      - ./redis/logs:/logs

